/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as privateTratorRouteRouteImport } from './routes/(private)/trator/route'
import { Route as privateadminRouteRouteImport } from './routes/(private)/(admin)/route'
import { Route as privateadminMaisRouteImport } from './routes/(private)/(admin)/mais'
import { Route as privateadminDespesasRouteImport } from './routes/(private)/(admin)/despesas'
import { Route as privateadminDashboardRouteImport } from './routes/(private)/(admin)/dashboard'
import { Route as privateTratorwithNavbarRouteRouteImport } from './routes/(private)/trator/(with-navbar)/route'
import { Route as privateadminServicosIndexRouteImport } from './routes/(private)/(admin)/servicos/index'
import { Route as privateTratorServicoNovoRouteImport } from './routes/(private)/trator/servico/novo'
import { Route as privateTratorwithNavbarServicosRouteImport } from './routes/(private)/trator/(with-navbar)/servicos'
import { Route as privateTratorwithNavbarHorasRouteImport } from './routes/(private)/trator/(with-navbar)/horas'
import { Route as privateadminServicosIdPagamentoRouteImport } from './routes/(private)/(admin)/servicos/$id/pagamento'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const privateTratorRouteRoute = privateTratorRouteRouteImport.update({
  id: '/trator',
  path: '/trator',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateadminRouteRoute = privateadminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateadminMaisRoute = privateadminMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => privateadminRouteRoute,
} as any)
const privateadminDespesasRoute = privateadminDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => privateadminRouteRoute,
} as any)
const privateadminDashboardRoute = privateadminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => privateadminRouteRoute,
} as any)
const privateTratorwithNavbarRouteRoute =
  privateTratorwithNavbarRouteRouteImport.update({
    id: '/(with-navbar)',
    getParentRoute: () => privateTratorRouteRoute,
  } as any)
const privateadminServicosIndexRoute =
  privateadminServicosIndexRouteImport.update({
    id: '/servicos/',
    path: '/servicos/',
    getParentRoute: () => privateadminRouteRoute,
  } as any)
const privateTratorServicoNovoRoute =
  privateTratorServicoNovoRouteImport.update({
    id: '/servico/novo',
    path: '/servico/novo',
    getParentRoute: () => privateTratorRouteRoute,
  } as any)
const privateTratorwithNavbarServicosRoute =
  privateTratorwithNavbarServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => privateTratorwithNavbarRouteRoute,
  } as any)
const privateTratorwithNavbarHorasRoute =
  privateTratorwithNavbarHorasRouteImport.update({
    id: '/horas',
    path: '/horas',
    getParentRoute: () => privateTratorwithNavbarRouteRoute,
  } as any)
const privateadminServicosIdPagamentoRoute =
  privateadminServicosIdPagamentoRouteImport.update({
    id: '/servicos/$id/pagamento',
    path: '/servicos/$id/pagamento',
    getParentRoute: () => privateadminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/not-found': typeof NotFoundRoute
  '/trator': typeof privateTratorwithNavbarRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/dashboard': typeof privateadminDashboardRoute
  '/despesas': typeof privateadminDespesasRoute
  '/mais': typeof privateadminMaisRoute
  '/trator/horas': typeof privateTratorwithNavbarHorasRoute
  '/trator/servicos': typeof privateTratorwithNavbarServicosRoute
  '/trator/servico/novo': typeof privateTratorServicoNovoRoute
  '/servicos/': typeof privateadminServicosIndexRoute
  '/servicos/$id/pagamento': typeof privateadminServicosIdPagamentoRoute
}
export interface FileRoutesByTo {
  '/not-found': typeof NotFoundRoute
  '/trator': typeof privateTratorwithNavbarRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/dashboard': typeof privateadminDashboardRoute
  '/despesas': typeof privateadminDespesasRoute
  '/mais': typeof privateadminMaisRoute
  '/trator/horas': typeof privateTratorwithNavbarHorasRoute
  '/trator/servicos': typeof privateTratorwithNavbarServicosRoute
  '/trator/servico/novo': typeof privateTratorServicoNovoRoute
  '/servicos': typeof privateadminServicosIndexRoute
  '/servicos/$id/pagamento': typeof privateadminServicosIdPagamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(private)': typeof privateRouteRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/(private)/(admin)': typeof privateadminRouteRouteWithChildren
  '/(private)/trator': typeof privateTratorRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(private)/trator/(with-navbar)': typeof privateTratorwithNavbarRouteRouteWithChildren
  '/(private)/(admin)/dashboard': typeof privateadminDashboardRoute
  '/(private)/(admin)/despesas': typeof privateadminDespesasRoute
  '/(private)/(admin)/mais': typeof privateadminMaisRoute
  '/(private)/trator/(with-navbar)/horas': typeof privateTratorwithNavbarHorasRoute
  '/(private)/trator/(with-navbar)/servicos': typeof privateTratorwithNavbarServicosRoute
  '/(private)/trator/servico/novo': typeof privateTratorServicoNovoRoute
  '/(private)/(admin)/servicos/': typeof privateadminServicosIndexRoute
  '/(private)/(admin)/servicos/$id/pagamento': typeof privateadminServicosIdPagamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/not-found'
    | '/trator'
    | '/login'
    | '/dashboard'
    | '/despesas'
    | '/mais'
    | '/trator/horas'
    | '/trator/servicos'
    | '/trator/servico/novo'
    | '/servicos/'
    | '/servicos/$id/pagamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/not-found'
    | '/trator'
    | '/login'
    | '/dashboard'
    | '/despesas'
    | '/mais'
    | '/trator/horas'
    | '/trator/servicos'
    | '/trator/servico/novo'
    | '/servicos'
    | '/servicos/$id/pagamento'
  id:
    | '__root__'
    | '/(auth)'
    | '/(private)'
    | '/not-found'
    | '/(private)/(admin)'
    | '/(private)/trator'
    | '/(auth)/login'
    | '/(private)/trator/(with-navbar)'
    | '/(private)/(admin)/dashboard'
    | '/(private)/(admin)/despesas'
    | '/(private)/(admin)/mais'
    | '/(private)/trator/(with-navbar)/horas'
    | '/(private)/trator/(with-navbar)/servicos'
    | '/(private)/trator/servico/novo'
    | '/(private)/(admin)/servicos/'
    | '/(private)/(admin)/servicos/$id/pagamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  privateRouteRoute: typeof privateRouteRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(private)/trator': {
      id: '/(private)/trator'
      path: '/trator'
      fullPath: '/trator'
      preLoaderRoute: typeof privateTratorRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/(admin)': {
      id: '/(private)/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateadminRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/(admin)/mais': {
      id: '/(private)/(admin)/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof privateadminMaisRouteImport
      parentRoute: typeof privateadminRouteRoute
    }
    '/(private)/(admin)/despesas': {
      id: '/(private)/(admin)/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof privateadminDespesasRouteImport
      parentRoute: typeof privateadminRouteRoute
    }
    '/(private)/(admin)/dashboard': {
      id: '/(private)/(admin)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privateadminDashboardRouteImport
      parentRoute: typeof privateadminRouteRoute
    }
    '/(private)/trator/(with-navbar)': {
      id: '/(private)/trator/(with-navbar)'
      path: ''
      fullPath: '/trator'
      preLoaderRoute: typeof privateTratorwithNavbarRouteRouteImport
      parentRoute: typeof privateTratorRouteRoute
    }
    '/(private)/(admin)/servicos/': {
      id: '/(private)/(admin)/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof privateadminServicosIndexRouteImport
      parentRoute: typeof privateadminRouteRoute
    }
    '/(private)/trator/servico/novo': {
      id: '/(private)/trator/servico/novo'
      path: '/servico/novo'
      fullPath: '/trator/servico/novo'
      preLoaderRoute: typeof privateTratorServicoNovoRouteImport
      parentRoute: typeof privateTratorRouteRoute
    }
    '/(private)/trator/(with-navbar)/servicos': {
      id: '/(private)/trator/(with-navbar)/servicos'
      path: '/servicos'
      fullPath: '/trator/servicos'
      preLoaderRoute: typeof privateTratorwithNavbarServicosRouteImport
      parentRoute: typeof privateTratorwithNavbarRouteRoute
    }
    '/(private)/trator/(with-navbar)/horas': {
      id: '/(private)/trator/(with-navbar)/horas'
      path: '/horas'
      fullPath: '/trator/horas'
      preLoaderRoute: typeof privateTratorwithNavbarHorasRouteImport
      parentRoute: typeof privateTratorwithNavbarRouteRoute
    }
    '/(private)/(admin)/servicos/$id/pagamento': {
      id: '/(private)/(admin)/servicos/$id/pagamento'
      path: '/servicos/$id/pagamento'
      fullPath: '/servicos/$id/pagamento'
      preLoaderRoute: typeof privateadminServicosIdPagamentoRouteImport
      parentRoute: typeof privateadminRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface privateadminRouteRouteChildren {
  privateadminDashboardRoute: typeof privateadminDashboardRoute
  privateadminDespesasRoute: typeof privateadminDespesasRoute
  privateadminMaisRoute: typeof privateadminMaisRoute
  privateadminServicosIndexRoute: typeof privateadminServicosIndexRoute
  privateadminServicosIdPagamentoRoute: typeof privateadminServicosIdPagamentoRoute
}

const privateadminRouteRouteChildren: privateadminRouteRouteChildren = {
  privateadminDashboardRoute: privateadminDashboardRoute,
  privateadminDespesasRoute: privateadminDespesasRoute,
  privateadminMaisRoute: privateadminMaisRoute,
  privateadminServicosIndexRoute: privateadminServicosIndexRoute,
  privateadminServicosIdPagamentoRoute: privateadminServicosIdPagamentoRoute,
}

const privateadminRouteRouteWithChildren =
  privateadminRouteRoute._addFileChildren(privateadminRouteRouteChildren)

interface privateTratorwithNavbarRouteRouteChildren {
  privateTratorwithNavbarHorasRoute: typeof privateTratorwithNavbarHorasRoute
  privateTratorwithNavbarServicosRoute: typeof privateTratorwithNavbarServicosRoute
}

const privateTratorwithNavbarRouteRouteChildren: privateTratorwithNavbarRouteRouteChildren =
  {
    privateTratorwithNavbarHorasRoute: privateTratorwithNavbarHorasRoute,
    privateTratorwithNavbarServicosRoute: privateTratorwithNavbarServicosRoute,
  }

const privateTratorwithNavbarRouteRouteWithChildren =
  privateTratorwithNavbarRouteRoute._addFileChildren(
    privateTratorwithNavbarRouteRouteChildren,
  )

interface privateTratorRouteRouteChildren {
  privateTratorwithNavbarRouteRoute: typeof privateTratorwithNavbarRouteRouteWithChildren
  privateTratorServicoNovoRoute: typeof privateTratorServicoNovoRoute
}

const privateTratorRouteRouteChildren: privateTratorRouteRouteChildren = {
  privateTratorwithNavbarRouteRoute:
    privateTratorwithNavbarRouteRouteWithChildren,
  privateTratorServicoNovoRoute: privateTratorServicoNovoRoute,
}

const privateTratorRouteRouteWithChildren =
  privateTratorRouteRoute._addFileChildren(privateTratorRouteRouteChildren)

interface privateRouteRouteChildren {
  privateadminRouteRoute: typeof privateadminRouteRouteWithChildren
  privateTratorRouteRoute: typeof privateTratorRouteRouteWithChildren
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateadminRouteRoute: privateadminRouteRouteWithChildren,
  privateTratorRouteRoute: privateTratorRouteRouteWithChildren,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  privateRouteRoute: privateRouteRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
