/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as privateTratorRouteRouteImport } from './routes/(private)/trator/route'
import { Route as privateadminRouteRouteImport } from './routes/(private)/(admin)/route'
import { Route as privateTratorServicosRouteImport } from './routes/(private)/trator/servicos'
import { Route as privateTratorHorasRouteImport } from './routes/(private)/trator/horas'
import { Route as privateadminDashboardRouteImport } from './routes/(private)/(admin)/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const privateTratorRouteRoute = privateTratorRouteRouteImport.update({
  id: '/(private)/trator',
  path: '/trator',
  getParentRoute: () => rootRouteImport,
} as any)
const privateadminRouteRoute = privateadminRouteRouteImport.update({
  id: '/(private)/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateTratorServicosRoute = privateTratorServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => privateTratorRouteRoute,
} as any)
const privateTratorHorasRoute = privateTratorHorasRouteImport.update({
  id: '/horas',
  path: '/horas',
  getParentRoute: () => privateTratorRouteRoute,
} as any)
const privateadminDashboardRoute = privateadminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => privateadminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/trator': typeof privateTratorRouteRouteWithChildren
  '/dashboard': typeof privateadminDashboardRoute
  '/trator/horas': typeof privateTratorHorasRoute
  '/trator/servicos': typeof privateTratorServicosRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/trator': typeof privateTratorRouteRouteWithChildren
  '/dashboard': typeof privateadminDashboardRoute
  '/trator/horas': typeof privateTratorHorasRoute
  '/trator/servicos': typeof privateTratorServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/(private)/(admin)': typeof privateadminRouteRouteWithChildren
  '/(private)/trator': typeof privateTratorRouteRouteWithChildren
  '/(private)/(admin)/dashboard': typeof privateadminDashboardRoute
  '/(private)/trator/horas': typeof privateTratorHorasRoute
  '/(private)/trator/servicos': typeof privateTratorServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/trator'
    | '/dashboard'
    | '/trator/horas'
    | '/trator/servicos'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/trator' | '/dashboard' | '/trator/horas' | '/trator/servicos'
  id:
    | '__root__'
    | '/login'
    | '/(private)/(admin)'
    | '/(private)/trator'
    | '/(private)/(admin)/dashboard'
    | '/(private)/trator/horas'
    | '/(private)/trator/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  privateadminRouteRoute: typeof privateadminRouteRouteWithChildren
  privateTratorRouteRoute: typeof privateTratorRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/trator': {
      id: '/(private)/trator'
      path: '/trator'
      fullPath: '/trator'
      preLoaderRoute: typeof privateTratorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/(admin)': {
      id: '/(private)/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateadminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/trator/servicos': {
      id: '/(private)/trator/servicos'
      path: '/servicos'
      fullPath: '/trator/servicos'
      preLoaderRoute: typeof privateTratorServicosRouteImport
      parentRoute: typeof privateTratorRouteRoute
    }
    '/(private)/trator/horas': {
      id: '/(private)/trator/horas'
      path: '/horas'
      fullPath: '/trator/horas'
      preLoaderRoute: typeof privateTratorHorasRouteImport
      parentRoute: typeof privateTratorRouteRoute
    }
    '/(private)/(admin)/dashboard': {
      id: '/(private)/(admin)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privateadminDashboardRouteImport
      parentRoute: typeof privateadminRouteRoute
    }
  }
}

interface privateadminRouteRouteChildren {
  privateadminDashboardRoute: typeof privateadminDashboardRoute
}

const privateadminRouteRouteChildren: privateadminRouteRouteChildren = {
  privateadminDashboardRoute: privateadminDashboardRoute,
}

const privateadminRouteRouteWithChildren =
  privateadminRouteRoute._addFileChildren(privateadminRouteRouteChildren)

interface privateTratorRouteRouteChildren {
  privateTratorHorasRoute: typeof privateTratorHorasRoute
  privateTratorServicosRoute: typeof privateTratorServicosRoute
}

const privateTratorRouteRouteChildren: privateTratorRouteRouteChildren = {
  privateTratorHorasRoute: privateTratorHorasRoute,
  privateTratorServicosRoute: privateTratorServicosRoute,
}

const privateTratorRouteRouteWithChildren =
  privateTratorRouteRoute._addFileChildren(privateTratorRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  privateadminRouteRoute: privateadminRouteRouteWithChildren,
  privateTratorRouteRoute: privateTratorRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
